; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = m5stack-cardputer

[env:m5stack-cardputer]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = arduino

upload_speed = 1500000
monitor_speed = 115200

board_build.filesystem = littlefs
board_build.partitions = partitions/luma-8mb.csv
extra_scripts = pre:tools/inject-luma-version.py

build_src_filter =
    +<*>
    -<luma/platform/host/>

build_flags =
    -DESP32S3
    -DCORE_DEBUG_LEVEL=5
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -std=gnu++17
    -DLUMA_BUILD_ENV=\"m5stack-cardputer\"

lib_deps =
    M5Cardputer=https://github.com/m5stack/M5Cardputer

monitor_filters =
    time
    esp32_exception_decoder

[env:native]
platform = native
test_framework = unity
test_build_src = true
platform_packages =
    toolchain-gccmingw32
extra_scripts = pre:tools/inject-luma-version.py
build_flags =
    -std=gnu++17
    -DLUMA_BUILD_ENV=\"native\"
build_src_filter =
    +<*>
    -<main.cpp>
    -<luma/platform/cardputer/>
