#!/usr/bin/env python3
"""Extract ASCII from Fusion Pixel 10px BDFs and write include/luma/ui/font.h.

The firmware build does not run this script. Re-run it when updating the
vendored ASCII BDF sources in assets/fonts/.
"""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets" / "fonts"
INCLUDE = ROOT / "include" / "luma" / "ui" / "font.h"

FIRST = 0x20
LAST = 0x7F
COUNT = LAST - FIRST + 1


def parse_ascii_glyphs(path: Path) -> tuple[int, int, list[list[int]]]:
    text = path.read_text(encoding="utf-8")
    glyphs: dict[int, list[int]] = {}
    encoding: int | None = None
    width = 0
    height = 0
    in_bitmap = False
    rows: list[int] = []

    def commit() -> None:
        nonlocal encoding, in_bitmap, rows
        if encoding is not None and FIRST <= encoding <= LAST:
            glyphs[encoding] = rows
        encoding = None
        in_bitmap = False
        rows = []

    for raw in text.splitlines():
        line = raw.strip()
        if line.startswith("ENCODING "):
            encoding = int(line.split()[1])
        elif line.startswith("DWIDTH ") and encoding is not None and FIRST <= encoding <= LAST:
            width = max(width, int(line.split()[1]))
        elif line.startswith("BBX ") and encoding is not None and FIRST <= encoding <= LAST:
            parts = line.split()
            height = max(height, int(parts[2]))
        elif line == "BITMAP":
            in_bitmap = encoding is not None and FIRST <= encoding <= LAST
            rows = []
        elif line == "ENDCHAR":
            commit()
        elif in_bitmap:
            bits = int(line, 16)
            shift = 16 - len(line) * 4
            if shift < 0:
                bits >>= -shift
                shift = 0
            rows.append(bits << shift)

    if width <= 0 or height <= 0:
        raise SystemExit(f"{path}: could not determine glyph size")
    if 0x3F not in glyphs:
        raise SystemExit(f"{path}: missing '?' glyph")

    table = []
    for code in range(FIRST, LAST + 1):
        if code in glyphs:
            table.append(glyphs[code])
            continue
        if code == 0x7F:
            table.append([0] * height)
            continue
        raise SystemExit(f"{path}: missing ASCII glyph {code}")
    for rows in table:
        if len(rows) != height:
            raise SystemExit(f"{path}: expected {height} rows, got {len(rows)}")
    return width, height, table


def write_ascii_bdf(path: Path, family: str, version: str, width: int, height: int,
                    table: list[list[int]]) -> None:
    lines = [
        "STARTFONT 2.1",
        f"FONT -Luma-{family}-10-100-75-75-C-{width * 10}-ISO10646-1",
        "SIZE 10 75 75",
        f"FONTBOUNDINGBOX {width} {height} 0 -1",
        "STARTPROPERTIES 3",
        f"FAMILY_NAME \"{family}\"",
        f"FONT_VERSION \"{version}\"",
        "COPYRIGHT \"Derived from Fusion Pixel Font / Fusion Bold Pixel Font (OFL-1.1)\"",
        "ENDPROPERTIES",
        f"CHARS {COUNT}",
    ]
    for index, rows in enumerate(table):
        code = FIRST + index
        lines.extend(
            [
                f"STARTCHAR u{code:04X}",
                f"ENCODING {code}",
                f"DWIDTH {width} 0",
                f"BBX {width} {height} 0 -1",
                "BITMAP",
            ]
        )
        for row in rows:
            hex_width = (width + 3) // 4
            bits = row >> (16 - hex_width * 4)
            lines.append(f"{bits:0{hex_width}X}")
        lines.append("ENDCHAR")
    lines.append("ENDFONT")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def format_table(name: str, table: list[list[int]]) -> str:
    blocks = []
    for index, rows in enumerate(table):
        code = FIRST + index
        glyph = ", ".join(f"0x{row:04X}" for row in rows)
        char = chr(code)
        if char == " ":
            label = "space"
        elif char == "\\":
            label = "backslash"
        elif code == 0x7F:
            label = "DEL"
        else:
            label = char
        blocks.append(f"    {{{glyph}}},  // {label}")
    body = "\n".join(blocks)
    return f"static const uint16_t {name}[{COUNT}][kGlyphHeight] = {{\n{body}\n}};\n"


def write_header(regular_w: int, bold_w: int, height: int, regular: list[list[int]],
                 bold: list[list[int]]) -> None:
    header = f"""#pragma once

#include "luma/core/display.h"

#include <cstdint>

// Luma UI bitmap font: ASCII 0x20-0x7F from Fusion Pixel 10px monospaced latin
// (regular) and Fusion Bold Pixel 10px monospaced latin (bold), OFL-1.1.
// Regenerated by tools/gen-ui-font.py. The firmware build does not run that script.
namespace luma {{
namespace font {{

constexpr int kGlyphWidth = {regular_w};
constexpr int kBoldGlyphWidth = {bold_w};
constexpr int kGlyphHeight = {height};
constexpr int kFirstCode = {FIRST};
constexpr int kGlyphCount = {COUNT};

{format_table("kRegular", regular)}
{format_table("kBold", bold)}
inline const uint16_t* glyphRows(char character, bool bold) {{
    unsigned char code = static_cast<unsigned char>(character);
    if (code < kFirstCode || code > {LAST}) {{
        code = static_cast<unsigned char>('?');
    }}
    return (bold ? kBold : kRegular)[code - kFirstCode];
}}

inline int glyphWidth(bool bold) {{
    return bold ? kBoldGlyphWidth : kGlyphWidth;
}}

inline int textWidth(const char* text, int size, bool bold = false) {{
    if (text == nullptr) {{
        return 0;
    }}
    const int scale = size < 1 ? 1 : size;
    int count = 0;
    for (const char* cursor = text; *cursor != '\\0'; ++cursor) {{
        ++count;
    }}
    return count * glyphWidth(bold) * scale;
}}

template <typename SetPixel>
void drawText(Point origin, TextStyle style, const char* text, SetPixel set_pixel) {{
    if (text == nullptr) {{
        return;
    }}
    const int scale = style.size < 1 ? 1 : style.size;
    const int width = glyphWidth(style.bold);
    int x = origin.x;
    for (const char* cursor = text; *cursor != '\\0'; ++cursor) {{
        const uint16_t* rows = glyphRows(*cursor, style.bold);
        for (int row = 0; row < kGlyphHeight; ++row) {{
            for (int column = 0; column < width; ++column) {{
                if ((rows[row] & static_cast<uint16_t>(0x8000u >> column)) == 0) {{
                    continue;
                }}
                for (int dy = 0; dy < scale; ++dy) {{
                    for (int dx = 0; dx < scale; ++dx) {{
                        set_pixel(x + column * scale + dx, origin.y + row * scale + dy,
                                  style.color);
                    }}
                }}
            }}
        }}
        x += width * scale;
    }}
}}

}}  // namespace font
}}  // namespace luma
"""
    INCLUDE.parent.mkdir(parents=True, exist_ok=True)
    INCLUDE.write_text(header, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--regular-bdf", type=Path, help="Upstream regular latin BDF")
    parser.add_argument("--bold-bdf", type=Path, help="Upstream bold latin BDF")
    args = parser.parse_args()

    ASSETS.mkdir(parents=True, exist_ok=True)
    regular_src = args.regular_bdf or ASSETS / "luma-ui-10px-regular.bdf"
    bold_src = args.bold_bdf or ASSETS / "luma-ui-10px-bold.bdf"

    regular_w, regular_h, regular = parse_ascii_glyphs(regular_src)
    bold_w, bold_h, bold = parse_ascii_glyphs(bold_src)
    if regular_h != bold_h:
        raise SystemExit(f"regular and bold glyph heights differ: {regular_h} vs {bold_h}")

    write_ascii_bdf(ASSETS / "luma-ui-10px-regular.bdf", "Luma UI", "regular", regular_w,
                    regular_h, regular)
    write_ascii_bdf(ASSETS / "luma-ui-10px-bold.bdf", "Luma UI Bold", "bold", bold_w, bold_h,
                    bold)
    write_header(regular_w, bold_w, regular_h, regular, bold)
    print(f"wrote {INCLUDE} (regular {regular_w}x{regular_h}, bold {bold_w}x{bold_h}, {COUNT} glyphs)")


if __name__ == "__main__":
    main()
